import {
  Atom,
  Banknote,
  BookOpen,
  Brain,
  Building2,
  Calculator,
  ChartNoAxesColumn,
  Cpu,
  Dna,
  Feather,
  FlaskConical,
  Globe2,
  GraduationCap,
  HeartPulse,
  Landmark,
  Languages,
  Leaf,
  Library,
  Mountain,
  Moon,
  Pill,
  Scale,
  Scroll,
  Sprout,
  Stethoscope,
  Trophy,
  Users,
  Wrench,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  atom: Atom,
  banknote: Banknote,
  "book-open": BookOpen,
  brain: Brain,
  "building-2": Building2,
  calculator: Calculator,
  "chart-column": ChartNoAxesColumn,
  cpu: Cpu,
  dna: Dna,
  feather: Feather,
  "flask-conical": FlaskConical,
  "globe-2": Globe2,
  "graduation-cap": GraduationCap,
  "heart-pulse": HeartPulse,
  landmark: Landmark,
  languages: Languages,
  leaf: Leaf,
  library: Library,
  moon: Moon,
  mountain: Mountain,
  pill: Pill,
  scale: Scale,
  scroll: Scroll,
  sprout: Sprout,
  stethoscope: Stethoscope,
  trophy: Trophy,
  users: Users,
  wrench: Wrench,
};

export const ICON_KEYS = Object.keys(ICONS);

export function CategoryIcon({ iconKey, className }: { iconKey?: string | null; className?: string }) {
  const Icon = ICONS[iconKey ?? ""] ?? BookOpen;
  return <Icon className={className} aria-hidden="true" />;
}
